spring.application.name=parksmart

spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:17010/railway?sslMode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=hZGsROhqrQJVAaxSHoXSpDEKWOKAFcpT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never

server.port=${PORT:8080}